### PR TITLE
Introduces external depth (#74) & a few fixes (incl. #69)

### LINKED ISSUE #69: Panic with EmptyHost
I'm getting the following panics;

```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: EmptyHost', src/scraper.rs:97:37
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Any', src/scraper.rs:150:9
```

Could be a link without host?

### PR DESCRIPTION
**Pull request by marchellodev**
## Motivation
A lot of modern websites rely on external domains (usually referred to as cnd domains) for their css, js, images, and other resources. Since SuckIT does not yet support downloading data from external domains (except for the bug when `//en.wikipedia.org` is treated as a relative path, (which I fixed)), it is impossible to properly download big and complex websites (#74).

Also, this patch fixes panic when trying to parse urls like `///tools.wmflabs.org/`, which returns `Empty host` error. I encountered this trying to download wikipedia. So, I think this PR should also close #69

## Notes
I almost have no experience with Rust, and I haven't yet implemented tests for the changes (I'm not really sure what is the best way to do this). So, please look at the code with extra scrutiny :). However, I have tested it on a few websites, and everything seems to work properly.

Also, `--edepth` (external depth) does not have a shortcut, since `-e` is used for excluding pattern. I'm not sure how this parameter should be renamed in order for shortcut to exist

### CODE REVIEW

File: src/scraper.rs [hunk 1]
```diff
@@ -182,16 +183,27 @@ impl Scraper {
 
         dom.find_urls_as_strings()
             .into_iter()
-            .filter(|candidate| Scraper::should_visit(candidate, &url))
+            .filter(|candidate| Scraper::should_visit(candidate))
             .for_each(|next_url| {
-                let mut next_full_url = url.join(&next_url).unwrap();
+                let mut url_to_parse = next_url.clone();
+                // If url is `///tools.wmflabs.org/`, the app crashes
```
Comment (CohenArthur) [inline src/scraper.rs:189]: This should be a `FIXME` comment rather than just a comment, and maybe we'll have to open an issue associated with that which we could reference here via its number.

Or are you saying that any URL with leading three slashes crashes the app? Which is why you remove it on the next line?

In that case, I think it would be better to add a generic comment, such as `// If the URL starts with three slashes, the app crashes. Replace them by two slashes`

File: src/scraper.rs [hunk 2]
```diff
@@ -182,16 +183,27 @@ impl Scraper {
...
+                if url_to_parse.starts_with("///") { url_to_parse = url_to_parse.replacen("///", "//", 1) }
```
Comment (CohenArthur) [inline src/scraper.rs:190]: I think this is part of the formatting fail haha. We just use `cargo fmt` for formatting, you can see how to install it [here](https://github.com/rust-lang/rustfmt#quick-start)

File: src/args.rs [hunk 3]
```diff
@@ -37,6 +37,14 @@ pub struct Args {
     )]
     pub depth: i32,
 
+
+    #[structopt(
+    long,
+    default_value = "0",
+    help = "Maximum recursion depth to reach when visiting external domains. 0 is the default and will ignore links that lead to external domains"
+    )]
+    pub edepth: i32,
```
[the remark this answers is not in the document]
Comment (marchellodev) [reply src/args.rs:46]: How about `outdepth` or maybe `edomainsdepth`?

File: src/scraper.rs (hunk 2 above)
Comment (marchellodev) [reply src/scraper.rs:190]: I am using clion and the rust plugin, which uses cargo fmt (as far as I understand)

File: src/scraper.rs (hunk 1 above)
Comment (marchellodev) [reply src/scraper.rs]: Fixed in the latest commit. Thanks!

File: src/args.rs (hunk 3 above)
[the remark this answers is not in the document]
Comment (CohenArthur) [reply src/args.rs:46]: `outdepth` sounds nice to me!

File: README.md [hunk 4]
```diff
@@ -28,7 +28,8 @@ your disk.
 |---|---|
 |`-h, --help`|Displays help information|
 |`-v, --verbose`|Activate Verbose output|
-|`-d, --depth`|Specify the level of depth to go to when visiting the website|
+|`-d, --depth`|Specify the level of depth to go to when visiting the website. Default is -1 (infinity)|
+|`--edepth`|Specify the level of depth to go to when visiting websites that have a different domain name. Default is 0 (ignore external links)|
```
Comment (Skallwar) [inline README.md:32]: Add -1 as infinity as well

File: src/args.rs (hunk 3 above)
[the remark this answers is not in the document]
Comment (Skallwar) [reply src/args.rs:46]: What do you thinks of ``--extdepth``? I find ``out`` a bit weird but why not? We can always change further down the line if we are not happy

File: src/scraper.rs [hunk 5]
```diff
@@ -77,8 +77,8 @@ impl Scraper {
     }
 
     /// Push a new URL into the channel
-    fn push(transmitter: &Sender<(Url, i32)>, url: Url, depth: i32) {
-        if let Err(e) = transmitter.send((url, depth)) {
+    fn push(transmitter: &Sender<(Url, i32, i32)>, url: Url, depth: i32, edepth: i32) {
+        if let Err(e) = transmitter.send((url, depth, edepth)) {
```
Comment (Skallwar) [inline src/scraper.rs:81]: We will need to change ``edepth`` to whatever name we will chose on the other discussion.

File: src/scraper.rs [hunk 6]
```diff
@@ -140,9 +140,10 @@ impl Scraper {
     /// Proces an html file: add new url to the chanel and prepare for offline navigation
     fn handle_html(
         scraper: &Scraper,
-        transmitter: &Sender<(Url, i32)>,
+        transmitter: &Sender<(Url, i32, i32)>,
         url: &Url,
         depth: i32,
+        edepth: i32,
```
Comment (Skallwar) [inline src/scraper.rs:146]: Same here

File: src/scraper.rs [hunk 7]
```diff
@@ -182,16 +183,27 @@ impl Scraper {
...
-                let mut next_full_url = url.join(&next_url).unwrap();
+                let mut url_to_parse = next_url.clone();
+                // Without this line, if url is `///tools.wmflabs.org/`, the app crashes.
+                if url_to_parse.starts_with("///") { url_to_parse = url_to_parse.replacen("///", "//", 1) }
+
+                let mut next_full_url = match url.join(url_to_parse.as_str()) {
+                    Ok(url) => url,
+                    Err(e) => panic!("FAILED TO PARSE URL: {} | Error: {}", next_url, e)
+                };
+
```
Comment (Skallwar) [inline src/scraper.rs:196]: I think this should be a separate PR

File: src/scraper.rs [hunk 8]
```diff
@@ -182,16 +183,27 @@ impl Scraper {
...
                 let path = url_helper::to_path(&next_full_url);
 
                 if scraper.map_url_path(&next_full_url, path.clone())
-                    && (scraper.args.depth == INFINITE_DEPTH || depth < scraper.args.depth)
                 {
-                    Scraper::push(transmitter, next_full_url, depth + 1);
+                    if !Scraper::is_on_another_domain(&next_url, &url) && (scraper.args.depth == INFINITE_DEPTH || depth < scraper.args.depth) {
+                        Scraper::push(transmitter, next_full_url, depth + 1, edepth);
+                    } else if Scraper::is_on_another_domain(&next_url, &url) && (scraper.args.edepth == INFINITE_DEPTH || edepth < scraper.args.edepth) {
+                        Scraper::push(transmitter, next_full_url, depth, edepth + 1);
```
Comment (Skallwar) [inline src/scraper.rs:205]: The condition is getting to big. Please create a sub-function to do the check

File: src/scraper.rs [hunk 9]
```diff
@@ -313,19 +326,48 @@ impl Scraper {
...
+    /// If the URL leads to another domain
+    fn is_on_another_domain(url: &str, base: &Url) -> bool {
+        let mut real_url = String::from(url);
+
+        // TODO is this ok? :)
+        // `//en.wikipedia.org/` => `https://en.wikipedia.org/` AND `///tools.wmflabs.org/` => `https://tools.wmflabs.org`
+        // If we don't do that, `//en.wikipedia.org/` is considered a path, not a full url
+        // Therefore, another domain check gets ignored
+        if real_url.starts_with("///") {
+            real_url = real_url.replacen("///", "https://", 1);
```
Comment (Skallwar) [inline src/scraper.rs:354]: This seems to do the same thing than line 190. Maybe this can be refactored?

File: src/scraper.rs (hunk 7 above)
Comment (marchellodev) [reply src/scraper.rs:196]: I totally understand, but those are just a few lines. Can we please let this one slip? :)

File: src/scraper.rs (hunk 8 above)
Comment (marchellodev) [reply src/scraper.rs]: I have instead split two ifs into four :) I am not really sure how to have those conditions as a separate functions

File: src/scraper.rs [hunk 10]
```diff
@@ -313,19 +331,58 @@ impl Scraper {
...
+        let mut temp = data.clone();
+
+        if temp.starts_with("///") {
+            temp = data.replacen("///", "https://", 1);
+        }
+        if temp.starts_with("//") {
+            temp = data.replacen("//", "https://", 1);
+        }
+        temp
+    }
```
Comment (Skallwar) [inline src/scraper.rs:363]:
```suggestion
    fn normalize_url(data: String) -> String {
        if data.starts_with("///") {
            data.replacen("///", "https://", 1);
        } else if data.starts_with("//") {
            data.replacen("//", "https://", 1);
        } else {
           data
        }
    }
```
Is more idiomatic I think. This might not compile, check before applying

**Review by Skallwar — COMMENTED** [review]
Great work. Some nitpicks here and there. Thanks a lot

File: src/scraper.rs [hunk 11]
```diff
@@ -313,19 +331,58 @@ impl Scraper {
...
-    /// If a URL should be visited, or does it belong to another domain
-    fn should_visit(url: &str, base: &Url) -> bool {
+    /// If a URL should be visited (ignores `mail:`, `javascript:` and other pseudo-links)
+    fn should_visit(url: &str) -> bool {
         match Url::parse(url) {
+            /* The given candidate is a valid URL, and not a relative path to
+             * the next one. Therefore, we have to check if this URL is valid.
+             * If it is, we should visit it.
+             */
+            Ok(not_ok) => not_ok.has_host() && !not_ok.cannot_be_a_base(),
```
[the remark this answers is not in the document]
Comment (marchellodev) [reply src/scraper.rs:341]: When working on this, I have encountered a bug, where links that started with `tel:` or `javascript:` or `mailto:` would be added to the queue as well. This line helps filter out such links

File: src/scraper.rs (hunk 10 above)
Comment (marchellodev) [reply src/scraper.rs:363]: `data.replacen()` does not change the `data` variable as far as I understand. Also, `else if` should now be there, as there can be both `///` and `//` in the link.

Also this won't compile since only the last `else` clause returns some value

Comment (marchellodev) [reply src/scraper.rs]: I have just committed this code:

```rust
    fn normalize_url(url: String) -> String {
        if url.starts_with("///") {
            return url.replacen("///", "https://", 1);
        } else if url.starts_with("//") {
            return url.replacen("//", "https://", 1);
        }
        url
    }
```

File: src/scraper.rs (hunk 11 above)
[the remark this answers is not in the document]
Comment (Skallwar) [reply src/scraper.rs:341]: Ok thanks. Could you provide an url to a webpage with this kind of url in it (in order to create tests later on)

[the remark this answers is not in the document]
Comment (marchellodev) [reply src/scraper.rs:341]:
```html
<a href="javascript:alert(1)">Test page 1</a>
<a href="mailto:marchellodev@gmail.com">Test page 2</a>
```

**Comment by Skallwar** [comment]
You need to fix the coding style (use [rustfmt](https://github.com/rust-lang/rustfmt))

File: src/args.rs [hunk 12]
```diff
@@ -33,10 +33,17 @@ pub struct Args {
...
         default_value = "-1",
-        help = "Maximum recursion depth to reach when visiting. -1 is the default and will go as far as it can"
+        help = "Maximum recursion depth to reach when visiting. Default is -1 (infinity)"
     )]
     pub depth: i32,
 
+    #[structopt(
+        long,
+        default_value = "0",
+        help = "Maximum recursion depth to reach when visiting external domains. 0 is the default and will ignore links that lead to external domains."
```
Comment (CohenArthur) [inline src/args.rs:43]:
```suggestion
        help = "Maximum recursion depth to reach when visiting external domains. Default is 0. -1 means infinity"
```

File: src/scraper.rs [hunk 13]
```diff
@@ -313,29 +337,67 @@ impl Scraper {
...
+            /* Since we couldn't parse this "URL", then it must be a relative
+             * path or a malformed URL. If the URL is malformed, then it will
+             * be handled during the join() call in run() */
+            Err(_) => true,
+        }
+    }
+
+    /// Replaces `///` with `//`
+    /// And `//` with `https://`
+    /// Without this function, if url is `///tools.wmflabs.org/`, the app crashes.
```
Comment (CohenArthur) [inline src/scraper.rs:358]:
```suggestion
    /// Without this function, if url is `///<domain>.<extension>/`, the app crashes.
```
I think this is better. Otherwise, the comment makes it sound like using tools.wmflabs.org was the only buggy URL

File: src/scraper.rs [hunk 14]
```diff
@@ -313,29 +337,67 @@ impl Scraper {
...
+    }
+
+    /// If the URL leads to another domain
+    fn is_on_another_domain(url: &str, base: &Url) -> bool {
+        let real_url = Scraper::normalize_url(String::from(url));
+
+        // TODO is this ok? :)
+        // `//en.wikipedia.org/` => `https://en.wikipedia.org/` AND `///tools.wmflabs.org/` => `https://tools.wmflabs.org`
+        // If we don't do that, `//en.wikipedia.org/` is considered a path, not a full url
+        // Therefore, another domain check gets ignored
```
Comment (CohenArthur) [inline src/scraper.rs:375]: I'm assuming that this could be removed, right?

**Comment by Skallwar** [comment]
Please rebase on top of ``master`` and squash into one or two commit

**Review by Skallwar — APPROVED** [review]
Please rebase your branch on top of ``master`` and squash your commit into one or 2 commits

**Comment by Skallwar** [comment]
@marchellodev Can you still work on this? If not, I can rebase and add tests for you

**Comment by marchellodev** [comment]
@Skallwar I would really appreciate it! :) I tried to do that a few days ago, but I always stumbled upon some errors. I'm kinda new to git, especially to those sophisticated operations

Thanks again!

**Comment by Skallwar** [comment]
@CohenArthur are you ok with this?

**Review by CohenArthur — APPROVED** [review]
Looks good :D Thanks a lot @marchellodev

**Comment by Skallwar** [comment]
@marchellodev Thanks again, excellent work
