### PR TITLE
Fix scraping on URLs that have fragments

### LINKED ISSUE #116: suckit crashes when mirroring docs.sentry.io
suckit crashes when mirroring docs.sentry.io to disk. In the interest of reproducability and speed, a zipfile with all static contents is attached which for simulation purposes could be served with `python3 -mhttp.server` or [http-server](https://www.npmjs.com/package/http-server) or nginx (I recommend the npm package, it is easy to use and fast), and the [site is open-source so it can be built locally](https://github.com/getsentry/sentry-docs).

[public.zip](https://github.com/Skallwar/suckit/files/6527000/public.zip) -- this file is copyright Sentry and licensed under the [BSL](https://github.com/getsentry/sentry-docs/blob/master/LICENSE).

```
unzip public.zip
http-server public/ &
suckit -c -j200 http://localhost:8080/ -o copy-of-public/

thread '<unnamed>' panicked at 'Couldn't create suckit/localhost/platform-redirect/index.html?next=/configuration/releases/: Is a directory (os error 21)', src/logger.rs:42:9
```

Unrelated:

* I'd expect the query strings to be stripped or replaced in filenames and links, because when serving the mirrored sites, nginx will ignore them too.
* The output is also not pretty: All worker threads print panics because of poisoned locks.
* `-c` is ignored because it's a panic.

### PR DESCRIPTION
**Pull request by untitaker**
Fix #116

### CODE REVIEW

**Review by CohenArthur — APPROVED** [review]
Good catch, saves a clone!

File: src/scraper.rs [hunk 1]
```diff
@@ -184,15 +184,14 @@ impl Scraper {
             .into_iter()
             .filter(|candidate| Scraper::should_visit(candidate, &url))
             .for_each(|next_url| {
-                let next_full_url = url.join(&next_url).unwrap();
+                let mut next_full_url = url.join(&next_url).unwrap();
+                next_full_url.set_fragment(None);
```
Comment (Skallwar) [inline src/scraper.rs:188]: If you do this, you will not download the correct webpage. For example: ``http://xxxx.xxx/test?name=foo`` prints ``foo.png`` and ``http://xxxx.xxx/test?name=bar`` prints ``bar.png``. This will attempt to download ``http://xxxx.xxx/test`` and the content will not be correct

Comment (Skallwar) [reply src/scraper.rs:188]: Huuu. That already what we are doing, sorry. Maybe we should just never do a ``.set_fragment(None)``

Comment (untitaker) [reply src/scraper.rs:188]: You're talking about query strings, fragments are `#` anchors on the page.

Comment (Skallwar) [reply src/scraper.rs:188]: Ohh ok, my bad

**Review by Skallwar — APPROVED** [review]
